### ISSUE TITLE
Class formatting in the editor

### ISSUE THREAD

**Issue by Crednib** [NewPath-Consulting/ez-wildapricot-webdesigner#104]
Should we add to our instructions that a class can also start with a "." just in case they also try the manual inspect mode?

**Comment by asirota** [comment]
We sort of want to get them away from using DevTools unless they REALLY want to. In Dev Tools sometimes you get information that is not exactly what you need and you start trying all sorts of options to "force" it. Usually that leads to other issues. I can put into the docs something about the format of classes and IDs, but if you use the Inspector panel buttons you should always get the . and the #

![image](https://user-images.githubusercontent.com/458134/189756029-2e56a679-00ee-408e-92e0-237e8de14bfd.png)
