### ISSUE TITLE
Using "Replace" function with the same text that it's replacing can cause an infiniate loop

### ISSUE THREAD

**Issue by mDisna** [NewPath-Consulting/ez-wildapricot-webdesigner#115]
If you use the `Replace` function and have the "Default Text" present in the "Replacement Text", it will create an infinite loop and crash the page.

**Example 1:**
```
Default Text: Home
Function: replace
Replacement Text: Home Page
```

**Example 2:**
```
Default Text: Home
Function: replace
Replacement Text: [ez-fa]home[/ez-fa]
```

**Comment by asirota** [comment]
One idea would be to catch the potential for a recursive reference like this and throw up an error message first. Of course handling this in code would be better to catch this error and break out after the replacement.

**Comment by mDisna** [comment]
Unfortunately with that first approach, adding things like the FA icon to the "Home" menu link won't be possible.

The code that loops through the elements comes from the beta version, and I don't (yet) see a way to break out.

**Comment by asirota** [comment]
Could we test where the original text is the same as the replacement text and skip those lines logging into the error log?

**Comment by asirota** [comment]
@mDisna have we ever addressed this issue? Or is it still possible to create an infinite loop?

**Comment by mDisna** [comment]
Yes, this has been addressed. If a possible infinite loop is detected, that line in the CSV is skipped and it added to the error log
