### ISSUE TITLE
enhancement request: support multiple browser tabs/windows

### ISSUE THREAD

**Issue by mklybor** [NewPath-Consulting/ez-wildapricot-webdesigner#126]
If the user has multiple windows/tabs open to the translated web site, the language must currently be the same in each. some users would like to see windows/tabs in different languages concurrently. e.g., one window in French, one in English, one in Spanish.

**Comment by mDisna** [comment]
You cannot navigate the site in different languages at the same time in the same browser.

They will need to open a different browser, ie: Chrome & Firefox
