### ISSUE TITLE
Error in install could break site "white screen of death"

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/ez-wildapricot-webdesigner#137]
Currently if the script breaks somehow during invokation it is possible that this CSS in the Global JS  install script

`<style>body{visibility: hidden;}</style>`

could render a site in accessible to anyone as it loads all the time, even in admin mode!

Instead of putting this code in the install script let's add this CSS change into the actual code that executes the changes, since this visibility off/visibility on tag only needs to be done while EZ makes the actual changes in the file.

**Comment by mDisna** [comment]
Addressed in branch 2.09

**Comment by asirota** [comment]
Thanks @mDisna have you tested this change to make sure it works ok? If so create a PR to master so we can add a new build to distribute.
