### ISSUE TITLE
replace_element replacement?

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/ez-wildapricot-webdesigner#139]
The older `replace_element` function was used on older sites. What would be a good replacement for this function? Would replace work or should we put replace_element back to make it backwards compatible?

Or is the new `replace` function the same way as replace_element if the default field text is provided?

**Comment by mDisna** [comment]
`replace` searches for and replaces a specific string.

What `replace_element` did was search for a specific string and replace the entire content of the node that it's found in  (basically working as like the `text` function).

Looking at the provided CSV, I think `replace`, `link`, `button`, and `text` should be able to be used instead.

I'll look into adding `replace_element` back.

**Comment by asirota** [comment]
> What `replace_element` did was search for a specific string and replace the entire content of the node that it's found in (basically working as like the `text` function).

but `text` does not search for a specific string like `replace_element` did so it's not quite the same. You're assuming that you simply want to replace the text in a target element not caring what was there so the conditional nature of `replace_element` is gone.

**Comment by mklybor2** [comment]
maybe "replace" would work in these cases. I know that there were situations where "text" would not work for some reason and only replace or replace_element would work. and these were situations where "text" seemed like the right move.  sorry I can't remember particulars. I will try to reproduce on test site. I am trying to remember where the particular behavior of replace_element was required. I.e., do the replacement of the whole text if a particular substring was found. thanks for looking into this.

**Comment by mDisna** [comment]
> but `text` does not search for a specific string like `replace_element` did so it's not quite the same

Yes, that's true - but you can target the element that has the string. I'm trying to think of a use case for replace_element but am coming up short.

In any case, i can't find any notes on why I removed this so I will add it back.
