### ISSUE TITLE
unable to inspect links

### ISSUE THREAD

**Issue by mklybor2** [NewPath-Consulting/ez-wildapricot-webdesigner#142]
When I try to inspect a link, it follow the link rather than bringing its properties up in the inspector.

**Comment by mDisna** [comment]
I will need more information to troubleshoot this, as it works correctly on my site. Can you provide the URL of the webpage it is not working on?

**Comment by mklybor2** [comment]
Aha. It was an email thread, not slack

I put a video on slack. Yes it was in the member directory.
