### ISSUE TITLE
when getting a .csv syntax error, can the source be identified?

### ISSUE THREAD

**Issue by mklybor2** [NewPath-Consulting/ez-wildapricot-webdesigner#143]
Getting an error that there is some issue in the .csv file. But no indication of where the error is. Can a line number or something like that be given? Perhaps the actual offending piece of text. The error message reads "SyntaxError: The string did not match the expected pattern."

It gets part way through, and does translate some of the page.

![image](https://user-images.githubusercontent.com/117687677/228687148-893d6c6c-b53d-4d8e-a5a3-776649a02d5c.png)

**Comment by mDisna** [comment]
Can you provide the URL that you are getting this error on?

**Comment by mklybor2** [comment]
Try this one

https://icoa48.wildapricot.org/DirectoryTest

It’s public

It translates a bit of the page and then gets the error

And when in inspector mode, if you click on the link to the member’s name, it follows the link rather than inspecting it.

Thanks!

**Comment by mDisna** [comment]
This is the error that is showing in the console for that page:

```
[watm Error] DOMException: Document.querySelectorAll: 'div.fieldLabel span:contains(Bundle limit)' is not a valid selector functions.js:289:11
```

The `:contains()` selector is invalid.

**Comment by mklybor2** [comment]
Thanks will see how that is being used. Sent from my iPhoneOn Mar 29, 2023, at 10:42 PM, mDisna ***@***.***> wrote:﻿
This is the error that is showing in the console for that page:
[watm Error] DOMException: Document.querySelectorAll: 'div.fieldLabel span:contains(Bundle limit)' is not a valid selector functions.js:289:11

The :contains() selector is invalid.

**Comment by mklybor2** [comment]
This selector is in the existing production version of the web site, and it is working.

We copied over the exiting translation file unchanged. (Except to change some of the function names like shortdelay)

There are a lot of similar selectors.

Starting a slack thread on this.

**Comment by mDisna** [comment]
It may have worked in the previous version, but it will not work with the new one. Looking at the CSV, you are using that to target an element with a specified text, and then replace the text in that element. This would be a use case for `replace_element`

### Current configuration:
| Default Text | Replacement Text | Function | Query
| ------------ | ----------------- | -------- | -----
| Bundle limit | Maximum number of rights holders | <kbd>text</kbd> | <kbd>div.fieldLabel span:contains(Bundle limit)</kbd>

### Replace with
| Default Text | Replacement Text | Function | Query
| ------------ | ----------------- | -------- | -----
| Bundle limit | Maximum number of rights holders | <kbd>replace_element</kbd> | <kbd>div.fieldLabel span</kbd>

**Comment by mklybor2** [comment]
Ok will give this go.Sent from my iPhoneOn Apr 3, 2023, at 12:15 PM, mDisna ***@***.***> wrote:﻿
It may have worked in the previous version, but it will not work with the new one. Looking at the CSV, you are using that to target an element with a specified text, and then replace the text in that element. This would be a use case for replace_element
Current configuration:



Default Text
Replacement Text
Function
Query




Bundle limit
Maximum number of rights holders
text
div.fieldLabel span:contains(Bundle limit)



Replace with



Default Text
Replacement Text
Function
Query




Bundle limit
Maximum number of rights holders
replace_element
div.fieldLabel span
