### ISSUE TITLE
enablic_public_editor set to false should disable editor when shown to the public

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/ez-wildapricot-webdesigner#144]
currently the enable_public_editor = true; in the configuration script shows the editor when not logged in as an admin.

When going to production the ideal configuration would be that when logged in as an admin the EZ badge shows, but when logged out of admin the badge should not show to the public.

So by default the enable_public_editor should be set to false in the code and also set this CSS as well so that when logged out of admin the ez design icon doesn't show.

.publicContentView .watm-icon {
  display: none;
}

**Comment by asirota** [comment]
Yes that makes sense. The default when set to `false `should remove the branding and badge in the public view unless you're logged in to admin.  If set to true then enable the badge in public and admin view and allow opening it up.

**Comment by asirota** [comment]
How about we do this?

enable_public_editor=true;  by default in the install script so is available for everyone (admin and non-admin) in the public view for editing the file.

when you deploy to production, you must change the install script to have

enable_public_editor = false; 


Which will  hide the EZ badge icon in all views and frames.

**Comment by mDisna** [comment]
Reviewing the code, I did implement a separate flag for hiding the icon already: `hideWATMIcon = true;`

It is set to <kbd>false</kbd> by default.
