### ISSUE TITLE
Add a Copy Element ID auxiliary button to the CSS Path

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/ez-wildapricot-webdesigner#150]
If an ID exists in the CSS Path line, add another button to the right of the path allowing JUST the Element ID (#Abc123) to be copied from the CSS Path

This will allow the user to select the CSS Element ID in case the CSS Path is not working for the Query which sometimes happens with CSS Paths that contain deeply nested n-child(#)  pseudo-elements.

**Comment by asirota** [comment]
@mDisna is this actually working in 2.1.1?

**Comment by mDisna** [comment]
@asirota no, not in 2.1.1

**Comment by asirota** [comment]
@mDisna can you check in this change into 2.1.2 branch as well?

**Comment by mDisna** [comment]
Should this copy the that exists in somewhere in the path, or the ID of the selected element? Because currently if the selected element has an ID, the CSS path is equal to the ID.

**Comment by asirota** [comment]
The copy ID should only copy the ID at the start of the css path if one exists. If the Id is In the middle of the css path it should not offer a copy id button.

**Comment by mDisna** [comment]
I don't follow. Here are the 2 possible formats for the CSS path:

1. `#libraryTableHeader0 > tr > th:nth-child(2)`
2. `#idFooterPoweredByContainer`

If the selected element has an ID (example 2), then that is what the the CSS path would be and what would be copied with the [Copy CSS Path] button.

If the selected element doesn't have an id, then you get a path starting from the deepest ID found (example 1). Do you want the copy ID button to appear for example 1 and place `#libraryTableHeader0` in the clipboard despite it not being the selected element?

**Comment by asirota** [comment]
> If the selected element doesn't have an id, then you get a path starting from the deepest ID found (example 1). Do you want the copy ID button to appear for example 1 and place `#libraryTableHeader0` in the clipboard despite it not being the selected element?

Yes that's the idea. If the CSS Path has more than just the ID I'd like to give the option to copy just the ID because sometimes targeting that has the same effect and eliminates the possibility that a change in the order of an element changes the targeting. Also sometimes the CSS Path like this doesn't work but targeting the whole ID does.
