### ISSUE TITLE
allow multiple ez-library macros to be rendered separately on one gadget or one page

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/ez-wildapricot-webdesigner#153]
if you have two ez-libary instances on one gadget, they are merged together so that all documents appear in one library.

If the ez-library macros  are added across multiple gadgets, only the last ez-library macro appears

Change the functionality so that every ez-library instance shows a separate library no matter whether they are in 1 gadget or multiple gadgets. Ensure this also works on multi-lingual mode (eg 1 english ez-library, 2+ english ez-library, 1 french ez-library, 2+ ez-library instances)

**Comment by mDisna** [comment]
[76f61e9](https://github.com/NewPath-Consulting/ez-wildapricot-webdesigner/commit/76f61e9a389a558c99380612c64efad7a4a8e16f) allows for multiple libraries, however, they must be added to separate gadgets.

**Comment by asirota** [comment]
@mDisna seems if I have 2 ez-library tags in one gadget it seems to work one just fine, of course for multilingual they must be in separate gadgets but for 1 language one gadget seems to work fine.

**Comment by mDisna** [comment]
@asirota Two library tags in the same gadget will be combined into one library.

**Comment by asirota** [comment]
@mDisna I don't see that while testing 2 tags in one gadget here: https://newpathconsulting.wildapricot.org/

![image](https://github.com/NewPath-Consulting/ez-wildapricot-webdesigner/assets/458134/92633ff5-2e3f-4b9f-8d40-0d31b7c09f6a)

**Comment by mDisna** [comment]
@asirota Correction - two tags in the same _element_ will combine. It will work correctly if within separate <p> tags.

If you are using the HTML gadget and do not include <p> tags, it will combine. It is also looking for the deepest child element, so if within one gadget, one library tag is in a <p> tag (or some other tag) one one isn't, only the one in the html tag will render.
