### ISSUE TITLE
Automatic CSV Backups

### ISSUE THREAD

**Issue by mDisna** [NewPath-Consulting/ez-wildapricot-webdesigner#156]
Implement a flag for the JavaScript setup configuration to enable automatic backups.

**Flag:** `watm_saves_before_backup`
**Value:** `0` (off) - _`n`_ (any positive number)

**Question:** What should the default value be? Off or a specific save number?

Whenever a save is made to a CSV through the editor, a cookie is used to store the save number for that specific CSV. If the number of saves for a single CSV matches that of `watm_saves_before_backup`, then before overwriting that file, it is renamed by appending the current date and time to the filename. For example:

- `english.scv` becomes
- `english_2023-11-29_10.48.20.csv` (Y-m-d_G.i.s)

**Note/Limitations:**
- Since this is based on cookies, if the cookies are cleared between editing sessions (ie: the browser closes and cookies aren't preserved) then the counter would restart from zero.
- The count is stored separately for each file, and only file currently being edited will be backed up if it's save count matches the settings.

**Comment by asirota** [comment]
Does the save amount cookie expire? Or do we just keep the cookie on forever, just dividing the number of saves by the configurable value and if the remainder is 0 you do a backup?

**Comment by mDisna** [comment]
Cookie will not expire. If set to `0` (off) or `1` it probably will skip creating a cookie.

However, after each backup, the cookie value will be reset to zero rather than doing a `mod` calculation on an ongoing count.
