### ISSUE TITLE
add reference to the use of third party libraries

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/ez-wildapricot-webdesigner#162]
https://bossanova.uk/jspreadsheet
https://lokeshdhakar.com/projects/color-thief/
https://atomiks.github.io/tippyjs/
https://www.papaparse.com/

**Comment by Crednib** [comment]
I like the color thief but it doesn't look like it provides the hex so how
are you going to apply it?

Best regards,
Carol Binder, CRM/Database Migration/Formstack/QuickBooks for WildApricot
Follow us on  <https://www.facebook.com/newpathconsulting/> and
<https://www.instagram.com/newpathconsultingteam/>

**Comment by asirota** [comment]
if you click on an image and click View Properties button it extracts the color values out of the image -- try that with the inspector next time @Crednib

**Comment by asirota** [comment]
https://newpathconsulting.wildapricot.org/

**Comment by asirota** [comment]
![image](https://github.com/NewPath-Consulting/ez-wildapricot-webdesigner/assets/458134/cce7fef7-0f7a-41e0-bc80-5b8bcd80b7a2)

**Comment by Crednib** [comment]
Like it - how are you going to use it?
Best regards,
Carol Binder, CRM/Database Migration/Formstack/QuickBooks for WildApricot
Follow us on  <https://www.facebook.com/newpathconsulting/> and
<https://www.instagram.com/newpathconsultingteam/>

**Comment by asirota** [comment]
The hex codes can be added to style column on any property that accepts a color. Like font-color or background-color

**Comment by Crednib** [comment]
Is there a way to 'save' the hex codes to use later (in the style column)
or make them a drop down option?

Best regards,
Carol Binder, CRM/Database Migration/Formstack/QuickBooks for WildApricot
Follow us on  <https://www.facebook.com/newpathconsulting/> and
<https://www.instagram.com/newpathconsultingteam/>

**Comment by asirota** [comment]
Sure that’s a great idea. Can you put that in as a feature request here?

Alex Sirota, PMP                 PGP Public Key <https://bit.ly/asirotapgp>
Director at NewPath Consulting <https://newpathconsulting.com/>

Schedule a meeting easily, at a time that works for you.
<http://www.newpathconsulting.com/alex.html>

Be sure to follow us on social media!
<https://www.facebook.com/newpathconsulting>
<https://www.instagram.com/newpathconsultingteam/>

**Comment by asirota** [comment]
> https://bossanova.uk/jspreadsheet https://lokeshdhakar.com/projects/color-thief/ https://atomiks.github.io/tippyjs/ https://www.papaparse.com/

added to the readme.md file
