### ISSUE TITLE
Convert legacy style column to new format

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/ez-wildapricot-webdesigner#80]
In the pre 1.0 WATM the style column needed this formatting

{ "color" : "red", "font-style" : " italic" }

the 2.0 WATM needs  standard key value pairs delimited with ; (standard CSS)

color: red; font-style: italic;

when loading a config file, WATM should lint the style column and convert the JSON structure to standard css properties. When it does this it should alert the end user that

"EZ WildApricot Web Designer converted your configuration file to the modern format. xx lines were changed. Your configuration should operate without change."

**Comment by asirota** [comment]
if the conversion is too hard to do or problematic just warn when the style column has JSON

"EZ WildApricot Web Designer detected invalid characteres in your configuration file. Please convert the Style column to standard CSS properties (eg color: red; font-style: italic;)."

**Comment by mDisna** [comment]
@asirota After looking into this, the error you were receiving was from using double quotes anywhere in the editor. The latest push properly escapes these quotes so that error will no longer appear.

**Comment by asirota** [comment]
@mDisna if WATM encounters the old style JSON I would like an alert to appear to warn the user

"EZ WildApricot Web Designer detected invalid characteres in your configuration file. Please convert the Style column to standard CSS properties (eg color: red; font-style: italic;)."

Otherwise the JSON-style "style" column won't work and confuse.
