### ISSUE TITLE
right click menu -- copy/paste row

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/ez-wildapricot-webdesigner#98]
Is there a way to add a right click menu to the editor to add a copy row.

I know the copy/paste keyboard combo works but it would be nice to expose that option in the UI.

**Comment by mDisna** [comment]
Copy & Paste has been added to the context menu - however it is only working for a single cell at the moment

**Comment by asirota** [comment]
Single row I assume ?

**Comment by mDisna** [comment]
a single cell. You can copy and paste multiple rows and columns with the keyboard, but only one cell with the context menu. I'm looking into getting this to work properly with multiple columns & rows

**Comment by asirota** [comment]
Here's the Jspreadsheet CE repo https://bossanova.uk/jspreadsheet/v4/

**Comment by asirota** [comment]
won't implement
